development: 
  adapter: postgresql
  database: postgres
  password: 191192
  pool: 5
  timeout: 5000
  username: postgres
production: 
  adapter: postgresql
  database: postgres
  pool: 5
  timeout: 5000
test: 
  adapter: postgresql
  database: postgres
  pool: 5
  timeout: 5000